apiVersion: v1
data:
  CLICKHOUSE_HOST: clickhouse
  CLICKHOUSE_PORT_HTTP: "8123"
  CLICKHOUSE_PORT_TCP: "9000"
  DATABASE_PASSWORD: ds&bd2021-2022
  DATABASE_USER: admin
  ENVIRONMENT: dev
  KAFKA_HOST: kafka
  KAFKA_PORT: "9092"
  KAFKA_PORT_EXTERNAL: "9093"
  KAFKA_PORT_SECONDARY: "29092"
  KAFKA_TOPICS: measure_recordings,device_commands,test,sensors_metrics,measure_rollback
  MONGO_DB: conf
  MONGO_HOST: mongodb
  MONGO_INITDB_DATABASE: conf
  MONGO_INITDB_ROOT_PASSWORD: ds&bd2021-2022
  MONGO_INITDB_ROOT_USERNAME: admin
  MONGO_PASSWORD: ds&bd2021-2022
  MONGO_PORT: "27017"
  MONGO_SERVER: 0.0.0.0
  MONGO_USER: admin
  MQTT_BROKER_HOST: mosquitto
  MQTT_BROKER_PORT: "1883"
  MQTT_TOPIC_PREFIX: rmp/dsbd202122/
  POSTGRES_DB: recordings
  POSTGRES_EMAIL: admin@admin.com
  POSTGRES_HOST: postgres
  POSTGRES_PASSWORD: ds&bd2021-2022
  POSTGRES_PORT: "5432"
  POSTGRES_USERNAME: admin
  PROJECT_NAME1: monitoring-management-microservice
  PROJECT_NAME2: recording-microservice
  PROJECT_NAME3: analytics-microservice
  PROMETHEUS_HOST: prometheus
  PROMETHEUS_PORT: "9090"
  PUSHGATEWAY_HOST: pushgateway
  PUSHGATEWAY_PORT: "9091"
  RECORDING_MICROSERVICE_KAFKA_TOPICS: measure_recordings,device_commands,measure_rollback
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: analytics-microservice-env
  name: env
