apiVersion: v1
kind: Service
metadata:
  name: monitoring-management
  labels:
    svc: monitoring-management
spec:
  ports:
    - port: 8000
      protocol: TCP
      name: http
  selector:
    app: monitoring-management
---
apiVersion: v1
kind: Service
metadata:
  name: recording
  labels:
    svc: recording
spec:
  ports:
    - port: 8001
      protocol: TCP
      name: http
  selector:
    app: recording-microservice
---
apiVersion: v1
kind: Service
metadata:
  name: analytics
  labels:
    svc: analytics
spec:
  ports:
    - port: 8002
      protocol: TCP
      name: http
  selector:
    app: analytics-microservice
